import {
  PlayerPosition,
  PlayerPositionAbbreviation,
} from 'src/modules/players/domain/value-objects/player-position.enum';
import type { BenchSlotList, FormationConfigurationType } from './types';

export const FORMATION_CONFIGURATION: FormationConfigurationType = {
  '4-2-0': [
    {
      id: 'por',
      x: 50,
      y: 88,
      position: PlayerPosition.PORTERO,
      abbreviation: PlayerPositionAbbreviation.PO,
    },
    {
      id: 'def1',
      x: 20,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def2',
      x: 40,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def3',
      x: 60,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def4',
      x: 80,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'med1',
      x: 40,
      y: 40,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'med2',
      x: 60,
      y: 40,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
  ],
  '3-2-1': [
    {
      id: 'por',
      x: 50,
      y: 88,
      position: PlayerPosition.PORTERO,
      abbreviation: PlayerPositionAbbreviation.PO,
    },
    {
      id: 'def1',
      x: 30,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def2',
      x: 50,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def3',
      x: 70,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'med1',
      x: 40,
      y: 40,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'med2',
      x: 60,
      y: 40,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'del1',
      x: 50,
      y: 16,
      position: PlayerPosition.DELANTERO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.DC,
    },
  ],
  '3-1-2': [
    {
      id: 'por',
      x: 50,
      y: 88,
      position: PlayerPosition.PORTERO,
      abbreviation: PlayerPositionAbbreviation.PO,
    },
    {
      id: 'def1',
      x: 30,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def2',
      x: 50,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def3',
      x: 70,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'med1',
      x: 50,
      y: 40,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'del1',
      x: 40,
      y: 16,
      position: PlayerPosition.DELANTERO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.DC,
    },
    {
      id: 'del2',
      x: 60,
      y: 16,
      position: PlayerPosition.DELANTERO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.DC,
    },
  ],
  '2-3-1': [
    {
      id: 'por',
      x: 50,
      y: 88,
      position: PlayerPosition.PORTERO,
      abbreviation: PlayerPositionAbbreviation.PO,
    },
    {
      id: 'def1',
      x: 40,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def2',
      x: 60,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'med1',
      x: 30,
      y: 40,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'med2',
      x: 50,
      y: 40,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'med3',
      x: 70,
      y: 40,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'del1',
      x: 50,
      y: 16,
      position: PlayerPosition.DELANTERO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.DC,
    },
  ],
  '5-1-0': [
    {
      id: 'por',
      x: 50,
      y: 88,
      position: PlayerPosition.PORTERO,
      abbreviation: PlayerPositionAbbreviation.PO,
    },
    {
      id: 'def1',
      x: 16,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def2',
      x: 33,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def3',
      x: 50,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def4',
      x: 67,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def5',
      x: 84,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'med1',
      x: 50,
      y: 40,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
  ],
  '1-2-3': [
    {
      id: 'por',
      x: 50,
      y: 88,
      position: PlayerPosition.PORTERO,
      abbreviation: PlayerPositionAbbreviation.PO,
    },
    {
      id: 'def1',
      x: 50,
      y: 65,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'med1',
      x: 40,
      y: 40,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'med2',
      x: 60,
      y: 40,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'del1',
      x: 30,
      y: 16,
      position: PlayerPosition.DELANTERO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.DC,
    },
    {
      id: 'del2',
      x: 50,
      y: 16,
      position: PlayerPosition.DELANTERO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.DC,
    },
    {
      id: 'del3',
      x: 70,
      y: 16,
      position: PlayerPosition.DELANTERO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.DC,
    },
  ],
};

export const FORMATION_OPTIONS = [
  {
    label: '4-2-0',
    value: '4-2-0',
    description: 'Formación defensiva',
    players: '7 jugadores',
  },
  {
    label: '3-2-1',
    value: '3-2-1',
    description: 'Formación equilibrada',
    players: '7 jugadores',
  },
  {
    label: '3-1-2',
    value: '3-1-2',
    description: 'Formación ofensiva',
    players: '7 jugadores',
  },
  {
    label: '2-3-1',
    value: '2-3-1',
    description: 'Control del mediocampo',
    players: '7 jugadores',
  },
  {
    label: '5-1-0',
    value: '5-1-0',
    description: 'Máxima defensa',
    players: '7 jugadores',
  },
  {
    label: '1-2-3',
    value: '1-2-3',
    description: 'Máxima ofensiva',
    players: '7 jugadores',
  },
  {
    label: 'Personalizado',
    value: 'Personalizado',
    description: 'Formación personalizada',
    players: 'Posicionamiento libre',
  },
];

export const BENCH_SLOTS: BenchSlotList = [
  { id: 'bench1', label: 'Suplente 1' },
  { id: 'bench2', label: 'Suplente 2' },
  { id: 'bench3', label: 'Suplente 3' },
  { id: 'bench4', label: 'Suplente 4' },
  { id: 'bench5', label: 'Suplente 5' },
];
