import {
  PlayerPosition,
  PlayerPositionAbbreviation,
} from 'src/modules/players/domain/value-objects/player-position.enum';
import type {
  BenchSlotList,
  FormationConfigurationType,
  FormationOption,
} from 'src/modules/lineup-builder/types';

const POR_POSITION = {
  id: 'por',
  x: 0.5,
  y: 0.68,
  position: PlayerPosition.PORTERO,
  abbreviation: PlayerPositionAbbreviation.PO,
};

export const FORMATION_CONFIGURATION: FormationConfigurationType = {
  '4-2-0': [
    POR_POSITION,
    {
      id: 'def1',
      x: 0.1,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def2',
      x: 0.35,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def3',
      x: 0.65,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def4',
      x: 0.9,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'med1',
      x: 0.3,
      y: 0.3,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'med2',
      x: 0.7,
      y: 0.3,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
  ],
  '3-2-1': [
    POR_POSITION,
    {
      id: 'def1',
      x: 0.2,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def2',
      x: 0.5,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def3',
      x: 0.8,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'med1',
      x: 0.35,
      y: 0.3,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'med2',
      x: 0.65,
      y: 0.3,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'del1',
      x: 0.5,
      y: 0.1,
      position: PlayerPosition.DELANTERO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.DC,
    },
  ],
  '3-1-2': [
    POR_POSITION,
    {
      id: 'def1',
      x: 0.2,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def2',
      x: 0.5,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def3',
      x: 0.8,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'med1',
      x: 0.5,
      y: 0.3,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'del1',
      x: 0.3,
      y: 0.1,
      position: PlayerPosition.DELANTERO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.DC,
    },
    {
      id: 'del2',
      x: 0.7,
      y: 0.1,
      position: PlayerPosition.DELANTERO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.DC,
    },
  ],
  '2-3-1': [
    POR_POSITION,
    {
      id: 'def1',
      x: 0.3,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def2',
      x: 0.7,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'med1',
      x: 0.2,
      y: 0.3,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'med2',
      x: 0.5,
      y: 0.3,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'med3',
      x: 0.8,
      y: 0.3,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'del1',
      x: 0.5,
      y: 0.1,
      position: PlayerPosition.DELANTERO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.DC,
    },
  ],
  '5-1-0': [
    POR_POSITION,
    {
      id: 'def1',
      x: 0.05,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def2',
      x: 0.28,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def3',
      x: 0.5,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def4',
      x: 0.72,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'def5',
      x: 0.95,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'med1',
      x: 0.5,
      y: 0.3,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
  ],
  '1-2-3': [
    POR_POSITION,
    {
      id: 'def1',
      x: 0.5,
      y: 0.5,
      position: PlayerPosition.DEFENSA,
      abbreviation: PlayerPositionAbbreviation.DF,
    },
    {
      id: 'med1',
      x: 0.3,
      y: 0.3,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'med2',
      x: 0.7,
      y: 0.3,
      position: PlayerPosition.MEDIO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.MC,
    },
    {
      id: 'del1',
      x: 0.2,
      y: 0.1,
      position: PlayerPosition.DELANTERO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.DC,
    },
    {
      id: 'del2',
      x: 0.5,
      y: 0.1,
      position: PlayerPosition.DELANTERO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.DC,
    },
    {
      id: 'del3',
      x: 0.8,
      y: 0.1,
      position: PlayerPosition.DELANTERO_CENTRO,
      abbreviation: PlayerPositionAbbreviation.DC,
    },
  ],
};

export const FORMATION_OPTIONS: FormationOption[] = [
  {
    label: '4-2-0',
    value: '4-2-0',
    description: 'Formación defensiva',
    players: '7 jugadores',
  },
  {
    label: '3-2-1',
    value: '3-2-1',
    description: 'Formación equilibrada',
    players: '7 jugadores',
  },
  {
    label: '3-1-2',
    value: '3-1-2',
    description: 'Formación ofensiva',
    players: '7 jugadores',
  },
  {
    label: '2-3-1',
    value: '2-3-1',
    description: 'Control del mediocampo',
    players: '7 jugadores',
  },
  {
    label: '5-1-0',
    value: '5-1-0',
    description: 'Máxima defensa',
    players: '7 jugadores',
  },
  {
    label: '1-2-3',
    value: '1-2-3',
    description: 'Máxima ofensiva',
    players: '7 jugadores',
  },
  // {
  //   label: 'Personalizado',
  //   value: 'Personalizado',
  //   description: '',
  //   players: 'Posicionamiento libre',
  // },
];

export const DEFAULT_FORMATION = FORMATION_OPTIONS[1] as FormationOption;

export const BENCH_SLOTS: BenchSlotList = [
  { id: 'bench1', label: 'Suplente 1' },
  { id: 'bench2', label: 'Suplente 2' },
  { id: 'bench3', label: 'Suplente 3' },
  { id: 'bench4', label: 'Suplente 4' },
  { id: 'bench5', label: 'Suplente 5' },
];
